List data = [
  {
    'id' : 1,
    'name' : 'Timex',
    'title' : 'Stainless',
    'price' : 500,
  },
  {
    'id' : 2,
    'name' : 'Boat Smart Watch',
    'title' : 'With gold bracelet',
    'price' : 1500,
  },
  {
    'id' : 3,
    'name' : 'Sonata',
    'title' : 'Best look',
    'price' : 1100,
  },
  {
    'id' : 4,
    'name' : 'Limestone',
    'title' : 'For mens',
    'price' : 2500,
  },
  {
    'id' : 5,
    'name' : 'casio',
    'title' : 'Both mens & Womens',
    'price' : 2000,
  },
  {
    'id' : 6,
    'name' : 'Timex',
    'title' : 'leather finish',
    'price' : 1700,
  },
  {
    'id' : 1,
    'name' : 'Titan',
    'title' : 'Silver look',
    'price' : 5500,
  },
  {
    'id' : 1,
    'name' : 'Fastrack',
    'title' : 'wearable',
    'price' : 3500,
  },
  {
    'id' : 1,
    'name' : 'Fossil',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },
  {
    'id' : 1,
    'name' : 'Watch',
    'title' : 'wearable',
    'price' : 1500,
  },

];